services:
  frontend:
    build: frontend
    container_name: frontend
    ports:
      - 5173:80
#      - 443:443
    volumes:
      - ${SCANDAMUS_STATIC_SRCS_PATH}:/var/www/html

  django:
    build: django
    container_name: django
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG}
      - SUPABASE_HOST=${SUPABASE_HOST}
      - SUPABASE_USR=${SUPABASE_USR}
      - SUPABASE_PW=${SUPABASE_PW}
    ports:
      - "8000:8000"
    volumes:
      - ${SCANDAMUS_PATH}:/app
